# Stage 1

FROM 573967297194.dkr.ecr.us-east-1.amazonaws.com/maven:3.8.3 AS build

# Add maintainer, so that new user will understand who had written this Dockerfile
LABEL maintainer="shresthasaksham08@gmail.com"

# Add labels to the image to filter out if we have multiple application running
LABEL app=bankapp

# Set working directory
WORKDIR /src

# Copy source code from local to container
COPY . /src

# Build application and skip test cases
RUN mvn clean install -DskipTests=true

# Stage 2

# Import small size java image
FROM 573967297194.dkr.ecr.us-east-1.amazonaws.com/openjdk:17 AS deployer

# Copy build from stage 1 (builder)
COPY --from=build /src/target/*.jar /src/target/bankapp.jar

# Expose application port 
EXPOSE 8080

# Start the application
ENTRYPOINT ["java", "-jar", "/src/target/bankapp.jar"]
