apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bankapp.fullname" . }}-config
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.db.url | quote }}
