apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.mysql.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bankapp.name" . }}-mysql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bankapp.name" . }}-mysql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.db.name | quote }}
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$MYSQL_ROOT_PASSWORD\""]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          {{- with .Values.mysql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.mysql.storageClass }}
        storageClassName: {{ .Values.mysql.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
